image:
     file: .gitpod.dockerfile
ports:
  - port: 3000
tasks:
  - init: |
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
      nvm install 14.15.1
      nvm use 14.15.1
      export NG_CLI_ANALYTICS=ci
      npm install -g @angular/cli@11.0.7
      npm install -g http-server
      cd FindPetFriendsClient/
      npm i @bit/cagdas.pwaextendedcomponentscollection.pwa-header --save
      npm install
    command: |
      npm run start:prod
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod