import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class HelperService {

  constructor() { }

  getAllBreeds():string[]{
    return [
      "Affenpinscher",
      "Afghan Hound",
      "Aidi",
      "Airedale Terrier",
      "Akbash Dog",
      "Akita",
      "Alano Español",
      "Alaskan Klee Kai",
      "Alaskan Malamute",
      "Alpine Dachsbracke",
      "Alpine Spaniel",
      "American Bulldog",
      "American Cocker Spaniel",
      "American Eskimo Dog",
      "American Foxhound",
      "American Hairless Terrier",
      "American Pit Bull Terrier",
      "American Staffordshire Terrier",
      "American Water Spaniel",
      "Anglo-Français de Petite Vénerie",
      "Appenzeller Sennenhund",
      "Ariege Pointer",
      "Ariegeois",
      "Armant",
      "Armenian Gampr dog",
      "Artois Hound",
      "Australian Cattle Dog",
      "Australian Kelpie",
      "Australian Shepherd",
      "Australian Silky Terrier",
      "Australian Stumpy Tail Cattle Dog",
      "Australian Terrier",
      "Azawakh",
      "Bakharwal Dog",
      "Barbet",
      "Basenji",
      "Basque Shepherd Dog",
      "Basset Artésien Normand",
      "Basset Bleu de Gascogne",
      "Basset Fauve de Bretagne",
      "Basset Hound",
      "Bavarian Mountain Hound",
      "Beagle",
      "Beagle-Harrier",
      "Bearded Collie",
      "Beauceron",
      "Bedlington Terrier",
      "Belgian Shepherd Dog (Groenendael)",
      "Belgian Shepherd Dog (Laekenois)",
      "Belgian Shepherd Dog (Malinois)",
      "Bergamasco Shepherd",
      "Berger Blanc Suisse",
      "Berger Picard",
      "Berner Laufhund",
      "Bernese Mountain Dog",
      "Billy",
      "Black and Tan Coonhound",
      "Black and Tan Virginia Foxhound",
      "Black Norwegian Elkhound",
      "Black Russian Terrier",
      "Bloodhound",
      "Blue Lacy",
      "Blue Paul Terrier",
      "Boerboel",
      "Bohemian Shepherd",
      "Bolognese",
      "Border Collie",
      "Border Terrier",
      "Borzoi",
      "Boston Terrier",
      "Bouvier des Ardennes",
      "Bouvier des Flandres",
      "Boxer",
      "Boykin Spaniel",
      "Bracco Italiano",
      "Braque d'Auvergne",
      "Braque du Bourbonnais",
      "Braque du Puy",
      "Braque Francais",
      "Braque Saint-Germain",
      "Brazilian Terrier",
      "Briard",
      "Briquet Griffon Vendéen",
      "Brittany",
      "Broholmer",
      "Bruno Jura Hound",
      "Bucovina Shepherd Dog",
      "Bull and Terrier",
      "Bull Terrier (Miniature)",
      "Bull Terrier",
      "Bulldog",
      "Bullenbeisser",
      "Bullmastiff",
      "Bully Kutta",
      "Burgos Pointer",
      "Cairn Terrier",
      "Canaan Dog",
      "Canadian Eskimo Dog",
      "Cane Corso",
      "Cardigan Welsh Corgi",
      "Carolina Dog",
      "Carpathian Shepherd Dog",
      "Catahoula Cur",
      "Catalan Sheepdog",
      "Caucasian Shepherd Dog",
      "Cavalier King Charles Spaniel",
      "Central Asian Shepherd Dog",
      "Cesky Fousek",
      "Cesky Terrier",
      "Chesapeake Bay Retriever",
      "Chien Français Blanc et Noir",
      "Chien Français Blanc et Orange",
      "Chien Français Tricolore",
      "Chien-gris",
      "Chihuahua",
      "Chilean Fox Terrier",
      "Chinese Chongqing Dog",
      "Chinese Crested Dog",
      "Chinese Imperial Dog",
      "Chinook",
      "Chippiparai",
      "Chow Chow",
      "Cierny Sery",
      "Cimarrón Uruguayo",
      "Cirneco dell'Etna",
      "Clumber Spaniel",
      "Combai",
      "Cordoba Fighting Dog",
      "Coton de Tulear",
      "Cretan Hound",
      "Croatian Sheepdog",
      "Cumberland Sheepdog",
      "Curly Coated Retriever",
      "Cursinu",
      "Cão da Serra de Aires",
      "Cão de Castro Laboreiro",
      "Cão Fila de São Miguel",
      "Dachshund",
      "Dalmatian",
      "Dandie Dinmont Terrier",
      "Danish Swedish Farmdog",
      "Deutsche Bracke",
      "Doberman Pinscher",
      "Dogo Argentino",
      "Dogo Cubano",
      "Dogue de Bordeaux",
      "Drentse Patrijshond",
      "Drever",
      "Dunker",
      "Dutch Shepherd Dog",
      "Dutch Smoushond",
      "East Siberian Laika",
      "East-European Shepherd",
      "Elo",
      "English Cocker Spaniel",
      "English Foxhound",
      "English Mastiff",
      "English Setter",
      "English Shepherd",
      "English Springer Spaniel",
      "English Toy Terrier (Black &amp; Tan)",
      "English Water Spaniel",
      "English White Terrier",
      "Entlebucher Mountain Dog",
      "Estonian Hound",
      "Estrela Mountain Dog",
      "Eurasier",
      "Field Spaniel",
      "Fila Brasileiro",
      "Finnish Hound",
      "Finnish Lapphund",
      "Finnish Spitz",
      "Flat-Coated Retriever",
      "Formosan Mountain Dog",
      "Fox Terrier (Smooth)",
      "French Bulldog",
      "French Spaniel",
      "Galgo Español",
      "Gascon Saintongeois",
      "German Longhaired Pointer",
      "German Pinscher",
      "German Shepherd",
      "German Shorthaired Pointer",
      "German Spaniel",
      "German Spitz",
      "German Wirehaired Pointer",
      "Giant Schnauzer",
      "Glen of Imaal Terrier",
      "Golden Retriever",
      "Gordon Setter",
      "Gran Mastín de Borínquen",
      "Grand Anglo-Français Blanc et Noir",
      "Grand Anglo-Français Blanc et Orange",
      "Grand Anglo-Français Tricolore",
      "Grand Basset Griffon Vendéen",
      "Grand Bleu de Gascogne",
      "Grand Griffon Vendéen",
      "Great Dane",
      "Great Pyrenees",
      "Greater Swiss Mountain Dog",
      "Greek Harehound",
      "Greenland Dog",
      "Greyhound",
      "Griffon Bleu de Gascogne",
      "Griffon Bruxellois",
      "Griffon Fauve de Bretagne",
      "Griffon Nivernais",
      "Hamiltonstövare",
      "Hanover Hound",
      "Hare Indian Dog",
      "Harrier",
      "Havanese",
      "Hawaiian Poi Dog",
      "Himalayan Sheepdog",
      "Hokkaido",
      "Hovawart",
      "Huntaway",
      "Hygenhund",
      "Ibizan Hound",
      "Icelandic Sheepdog",
      "Indian pariah dog",
      "Indian Spitz",
      "Irish Red and White Setter",
      "Irish Setter",
      "Irish Terrier",
      "Irish Water Spaniel",
      "Irish Wolfhound",
      "Istrian Coarse-haired Hound",
      "Istrian Shorthaired Hound",
      "Italian Greyhound",
      "Jack Russell Terrier",
      "Jagdterrier",
      "Jämthund",
      "Kai Ken",
      "Kaikadi",
      "Kanni",
      "Karelian Bear Dog",
      "Karst Shepherd",
      "Keeshond",
      "Kerry Beagle",
      "Kerry Blue Terrier",
      "King Charles Spaniel",
      "King Shepherd",
      "Kintamani",
      "Kishu",
      "Komondor",
      "Kooikerhondje",
      "Koolie",
      "Korean Jindo Dog",
      "Kromfohrländer",
      "Kumaon Mastiff",
      "Kurī",
      "Kuvasz",
      "Kyi-Leo",
      "Labrador Husky",
      "Labrador Retriever",
      "Lagotto Romagnolo",
      "Lakeland Terrier",
      "Lancashire Heeler",
      "Landseer",
      "Lapponian Herder",
      "Large Münsterländer",
      "Leonberger",
      "Lhasa Apso",
      "Lithuanian Hound",
      "Longhaired Whippet",
      "Löwchen",
      "Mahratta Greyhound",
      "Maltese",
      "Manchester Terrier",
      "Maremma Sheepdog",
      "McNab",
      "Mexican Hairless Dog",
      "Miniature American Shepherd",
      "Miniature Australian Shepherd",
      "Miniature Fox Terrier",
      "Miniature Pinscher",
      "Miniature Schnauzer",
      "Miniature Shar Pei",
      "Molossus",
      "Montenegrin Mountain Hound",
      "Moscow Watchdog",
      "Moscow Water Dog",
      "Mountain Cur",
      "Mucuchies",
      "Mudhol Hound",
      "Mudi",
      "Neapolitan Mastiff",
      "New Zealand Heading Dog",
      "Newfoundland",
      "Norfolk Spaniel",
      "Norfolk Terrier",
      "Norrbottenspets",
      "North Country Beagle",
      "Northern Inuit Dog",
      "Norwegian Buhund",
      "Norwegian Elkhound",
      "Norwegian Lundehund",
      "Norwich Terrier",
      "Old Croatian Sighthound",
      "Old Danish Pointer",
      "Old English Sheepdog",
      "Old English Terrier",
      "Old German Shepherd Dog",
      "Olde English Bulldogge",
      "Otterhound",
      "Pachon Navarro",
      "Paisley Terrier",
      "Pandikona",
      "Papillon",
      "Parson Russell Terrier",
      "Patterdale Terrier",
      "Pekingese",
      "Pembroke Welsh Corgi",
      "Perro de Presa Canario",
      "Perro de Presa Mallorquin",
      "Peruvian Hairless Dog",
      "Petit Basset Griffon Vendéen",
      "Petit Bleu de Gascogne",
      "Phalène",
      "Pharaoh Hound",
      "Phu Quoc ridgeback dog",
      "Picardy Spaniel",
      "Plott Hound",
      "Podenco Canario",
      "Pointer (dog breed)",
      "Polish Greyhound",
      "Polish Hound",
      "Polish Hunting Dog",
      "Polish Lowland Sheepdog",
      "Polish Tatra Sheepdog",
      "Pomeranian",
      "Pont-Audemer Spaniel",
      "Poodle",
      "Porcelaine",
      "Portuguese Podengo",
      "Portuguese Pointer",
      "Portuguese Water Dog",
      "Posavac Hound",
      "Pražský Krysařík",
      "Pudelpointer",
      "Pug",
      "Puli",
      "Pumi",
      "Pungsan Dog",
      "Pyrenean Mastiff",
      "Pyrenean Shepherd",
      "Rafeiro do Alentejo",
      "Rajapalayam",
      "Rampur Greyhound",
      "Rastreador Brasileiro",
      "Rat Terrier",
      "Ratonero Bodeguero Andaluz",
      "Redbone Coonhound",
      "Rhodesian Ridgeback",
      "Rottweiler",
      "Rough Collie",
      "Russell Terrier",
      "Russian Spaniel",
      "Russian tracker",
      "Russo-European Laika",
      "Sabueso Español",
      "Saint-Usuge Spaniel",
      "Sakhalin Husky",
      "Saluki",
      "Samoyed",
      "Sapsali",
      "Schapendoes",
      "Schillerstövare",
      "Schipperke",
      "Schweizer Laufhund",
      "Schweizerischer Niederlaufhund",
      "Scotch Collie",
      "Scottish Deerhound",
      "Scottish Terrier",
      "Sealyham Terrier",
      "Segugio Italiano",
      "Seppala Siberian Sleddog",
      "Serbian Hound",
      "Serbian Tricolour Hound",
      "Shar Pei",
      "Shetland Sheepdog",
      "Shiba Inu",
      "Shih Tzu",
      "Shikoku",
      "Shiloh Shepherd Dog",
      "Siberian Husky",
      "Silken Windhound",
      "Sinhala Hound",
      "Skye Terrier",
      "Sloughi",
      "Slovak Cuvac",
      "Slovakian Rough-haired Pointer",
      "Small Greek Domestic Dog",
      "Small Münsterländer",
      "Smooth Collie",
      "South Russian Ovcharka",
      "Southern Hound",
      "Spanish Mastiff",
      "Spanish Water Dog",
      "Spinone Italiano",
      "Sporting Lucas Terrier",
      "St. Bernard",
      "St. John's water dog",
      "Stabyhoun",
      "Staffordshire Bull Terrier",
      "Standard Schnauzer",
      "Stephens Cur",
      "Styrian Coarse-haired Hound",
      "Sussex Spaniel",
      "Swedish Lapphund",
      "Swedish Vallhund",
      "Tahltan Bear Dog",
      "Taigan",
      "Talbot",
      "Tamaskan Dog",
      "Teddy Roosevelt Terrier",
      "Telomian",
      "Tenterfield Terrier",
      "Thai Bangkaew Dog",
      "Thai Ridgeback",
      "Tibetan Mastiff",
      "Tibetan Spaniel",
      "Tibetan Terrier",
      "Tornjak",
      "Tosa",
      "Toy Bulldog",
      "Toy Fox Terrier",
      "Toy Manchester Terrier",
      "Toy Trawler Spaniel",
      "Transylvanian Hound",
      "Treeing Cur",
      "Treeing Walker Coonhound",
      "Trigg Hound",
      "Tweed Water Spaniel",
      "Tyrolean Hound",
      "Vizsla",
      "Volpino Italiano",
      "Weimaraner",
      "Welsh Sheepdog",
      "Welsh Springer Spaniel",
      "Welsh Terrier",
      "West Highland White Terrier",
      "West Siberian Laika",
      "Westphalian Dachsbracke",
      "Wetterhoun",
      "Whippet",
      "White Shepherd",
      "Wire Fox Terrier",
      "Wirehaired Pointing Griffon",
      "Wirehaired Vizsla",
      "Yorkshire Terrier",
      "Šarplaninac"
    ];
  }

  getAustriaCities() : string[]{
    return [ "Absam",
    "Absdorf",
    "Abtenau",
    "Abtsdorf",
    "Ach",
    "Achenkirch",
    "Achensee",
    "Admont",
    "Adnet",
    "Afritz",
    "Aggsbach",
    "Aichbach",
    "Aichdorf",
    "Aifersdorf",
    "Aigen",
    "Aigen im Muehlkreis",
    "Ainet",
    "Aistersheim",
    "Alberndorf in der Riedmark",
    "Alberschwende",
    "Aldrans",
    "Alkoven",
    "Alland",
    "Allhartsberg",
    "Alpbach",
    "Altach",
    "Altenberg",
    "Altenberg bei Linz",
    "Altenburg",
    "Altendorf",
    "Altendorf",
    "Altenhof am Hausruck",
    "Altenmarkt an der Triesting",
    "Altenmarkt im Pongau",
    "Altheim",
    "Althofen",
    "Altlengbach",
    "Altlichtenwarth",
    "Altmunster",
    "Altwaidhofen",
    "Am See",
    "Amaliendorf",
    "Ampass",
    "Ampfelwang",
    "Amstetten",
    "Andorf",
    "Anger",
    "Anif",
    "Annenheim",
    "Ansfelden",
    "Anthering",
    "Apfelberg",
    "Arbesthal",
    "Ardagger Markt",
    "Ardning",
    "Arnoldstein",
    "Arriach",
    "Asberg",
    "Aschach an der Donau",
    "Aschau",
    "Aspang Markt",
    "Asparn",
    "Asperhofen",
    "Asten",
    "Attersee",
    "Attnang-Puchheim",
    "Atzbach",
    "Au",
    "Auersthal",
    "Aufhausen",
    "Augsdorf",
    "Aurolzmunster",
    "Axams",
    "Bach",
    "Bad Blumau",
    "Bad Deutsch-Altenburg",
    "Bad Erlach",
    "Bad Fischau",
    "Bad Gams",
    "Bad Gastein",
    "Bad Gleichenberg",
    "Bad Goisern",
    "Bad Hall",
    "Bad Hofgastein",
    "Bad Ischl",
    "Bad Kreuzen",
    "Bad Pirawarth",
    "Bad Radkersburg",
    "Bad Schallerbach",
    "Bad Tatzmannsdorf",
    "Bad Voslau",
    "Baden bei Wien",
    "Baernbach",
    "Baldramsdorf",
    "Bartholomaberg",
    "Barwies",
    "Bauer",
    "Baumgarten im Burgenland",
    "Baumgartenberg",
    "Baumkirchen",
    "Berg",
    "Bergau",
    "Bergheim",
    "Berndorf",
    "Bernhardsthal",
    "Bernstein",
    "Berwang",
    "Bezau",
    "Biberbach",
    "Biberwier",
    "Bichlbach",
    "Biedermann",
    "Biedermannsdorf",
    "Birgitz",
    "Bisamberg",
    "Bizau",
    "Bleiberg ob Villach",
    "Bleiburg",
    "Blindenmarkt",
    "Bludenz",
    "Bludesch",
    "Blumau",
    "Bockfliess",
    "Bodensdorf",
    "Boheimkirchen",
    "Bosendurnbach",
    "Bramberg am Wildkogel",
    "Brandberg",
    "Braunau am Inn",
    "Bregenz",
    "Breitenbrunn",
    "Breitenfurt bei Wien",
    "Breitenwang",
    "Brixen im Thale",
    "Bruck am Ziller",
    "Bruck an der Grossglocknerstrasse",
    "Bruck an der Leitha",
    "Bruck an der Mur",
    "Bruckl",
    "Bruckneudorf",
    "Bruendl",
    "Bruggen",
    "Brunn am Gebirge",
    "Buch",
    "Buch bei Jenbach",
    "Buchkirchen",
    "Burgkirchen",
    "Burgschleinitz",
    "Burmoos",
    "Dalaas",
    "Dechantskirchen",
    "Dellach",
    "Desselbrunn",
    "Deutsch Goritz",
    "Deutsch-Wagram",
    "Deutschfeistritz",
    "Deutschkreutz",
    "Deutschlandsberg",
    "Diepoltsham",
    "Dietach",
    "Dietersdorf am Gnasbach",
    "Dobersberg",
    "Dobersdorf",
    "Doblbach",
    "Dobldorf",
    "Doebriach",
    "Donnerskirchen",
    "Doren",
    "Dorf",
    "Dorfgastein",
    "Dorfla",
    "Dornbirn",
    "Drassburg",
    "Drassmarkt",
    "Dross",
    "Durnstein",
    "Ebbs",
    "Eben im Pongau",
    "Ebenau",
    "Ebendorf",
    "Ebenfurth",
    "Ebensee",
    "Ebenthal",
    "Ebergassing",
    "Eberndorf",
    "Eberschwang",
    "Ebersdorf",
    "Eberstein",
    "Ebreichsdorf",
    "Eckartsau",
    "Edelschrott",
    "Edelstal",
    "Edlitz",
    "Edt bei Lambach",
    "Eferding",
    "Egg",
    "Egg am Faaker See",
    "Eggenburg",
    "Eggendorf",
    "Eggendorf",
    "Eggendorf im Thale",
    "Eggersdorf bei Graz",
    "Ehrenhausen",
    "Ehrwald",
    "Eibiswald",
    "Eichgraben",
    "Eisbach",
    "Eisenberg",
    "Eisenerz",
    "Eisenstadt",
    "Eisentratten",
    "Eisgarn",
    "Elixhausen",
    "Ellmau",
    "Elsbethen",
    "Emberg",
    "Emmersdorf an der Donau",
    "Engelhartszell",
    "Engersdorf",
    "Engerwitzdorf",
    "Enns",
    "Ennsdorf",
    "Enzenkirchen",
    "Enzenreith",
    "Enzersdorf an der Fischa",
    "Enzersfeld",
    "Enzesfeld",
    "Erlauf",
    "Ernst",
    "Ernstbrunn",
    "Ernsthofen",
    "Erpersdorf",
    "Erpfendorf",
    "Esternberg",
    "Eugendorf",
    "Faak am See",
    "Falkenburg",
    "Fehring",
    "Feistritz",
    "Feistritz an der Drau",
    "Feld am See",
    "Feldbach",
    "Feldkirch",
    "Feldkirchen an der Donau",
    "Feldkirchen bei Graz",
    "Feldkirchen bei Mattighofen",
    "Feldkirchen in Karnten",
    "Felixdorf",
    "Ferndorf",
    "Fernitz",
    "Feuchten",
    "Feuersbrunn",
    "Fieberbrunn",
    "Filzmoos",
    "Finkenberg",
    "Finsing",
    "Fischamend Dorf",
    "Fischbach",
    "Fischerndorf",
    "Fiss",
    "Flachau",
    "Fladnitz im Raabtal",
    "Flattach",
    "Fliess",
    "Flinsdorf",
    "Foederlach",
    "Fohnsdorf",
    "Forst",
    "Frankenburg",
    "Frankenmarkt",
    "Frattingsdorf",
    "Frauenkirchen",
    "Freienstein",
    "Freilassing",
    "Freinberg",
    "Freistadt",
    "Friedburg",
    "Friesach",
    "Frohnleiten",
    "Fuernitz",
    "Fuerstenfeld",
    "Fugen",
    "Fulpmes",
    "Furthof",
    "Fusch an der Glocknerstrasse",
    "Fuschl am See",
    "Fussach",
    "Gaaden",
    "Gaal",
    "Gablitz",
    "Gaflenz",
    "Gailitz",
    "Gaisberg",
    "Gallbrunn",
    "Gallneukirchen",
    "Gallspach",
    "Gallzein",
    "Galtur",
    "Gaming",
    "Gampern",
    "Gansbach",
    "Ganserndorf",
    "Gargellen",
    "Gars am Kamp",
    "Garsten",
    "Gaschurn",
    "Gaspoltshofen",
    "Gasthof",
    "Gattendorf",
    "Gaweinstal",
    "Geinberg",
    "Geras",
    "Gerasdorf am Steinfelde",
    "Gerasdorf bei Wien",
    "Gerersdorf",
    "Gerlos",
    "Getzersdorf",
    "Gfohl",
    "Giesshubl",
    "Glan",
    "Glaubendorf",
    "Gleisdorf",
    "Glinzendorf",
    "Gloggnitz",
    "Gmund",
    "Gmunden",
    "Gnadenwald",
    "Gnas",
    "Gobelsburg",
    "Goedersdorf",
    "Goesselsdorf",
    "Gofis",
    "Going",
    "Goldegg",
    "Gollersdorf",
    "Golling an der Salzach",
    "Gols",
    "Gortipohl",
    "Gosau",
    "Gosdorf",
    "Gosing",
    "Gostling an der Ybbs",
    "Gotzendorf",
    "Gotzendorf an der Leitha",
    "Gotzens",
    "Gotzis",
    "Grabelsdorf",
    "Graen",
    "Grafenbach",
    "Grafendorf",
    "Grafendorf bei Hartberg",
    "Grafendorf bei Stainz",
    "Grafenschlag",
    "Grafenstein",
    "Grafenweg",
    "Grafenworth",
    "Gramastetten",
    "Gramatneusiedl",
    "Grambach",
    "Gratkorn",
    "Gratwein",
    "Graz",
    "Grein",
    "Gresten",
    "Gries",
    "Gries am Brenner",
    "Grieselstein",
    "Grieskirchen",
    "Griffen",
    "Grimmenstein",
    "Grobming",
    "Grodig",
    "Gross",
    "Gross-Enzersdorf",
    "Gross-Schweinbarth",
    "Gross-Siegharts",
    "Grossarl",
    "Grossebersdorf",
    "Grossklein",
    "Grosspesendorf",
    "Grossraming",
    "Grossrussbach",
    "Grossweikersdorf",
    "Grunbach am Schneeberg",
    "Gruner Baum",
    "Gschnitz",
    "Guessing",
    "Gugging",
    "Guglwald",
    "Gumpoldskirchen",
    "Gunselsdorf",
    "Gunskirchen",
    "Guntersdorf",
    "Guntramsdorf",
    "Gurten",
    "Gurtis",
    "Gutau",
    "Gutenstein",
    "Guttaring",
    "Haag",
    "Haag",
    "Haag am Hausruck",
    "Hadersdorf am Kamp",
    "Hadersfeld",
    "Hadres",
    "Hagenberg im Muhlkreis",
    "Haibach ob der Donau",
    "Haid",
    "Haidershofen",
    "Haiming",
    "Haimingerberg",
    "Hainburg an der Donau",
    "Hainfeld",
    "Halbturn",
    "Haldensee",
    "Hall",
    "Hall in Tirol",
    "Hallein",
    "Haller",
    "Hallstatt",
    "Harbach",
    "Hard",
    "Hart",
    "Hartberg",
    "Hartkirchen",
    "Haslau an der Donau",
    "Hatting",
    "Hatzendorf",
    "Haus",
    "Hausbrunn",
    "Hausleiten",
    "Hausmannstatten",
    "Hautzendorf",
    "Heidenreichstein",
    "Heiligenkreuz am Waasen",
    "Heimschuh",
    "Heissberg",
    "Heissingfelding",
    "Heiterwang",
    "Hellmonsodt",
    "Henndorf am Wallersee",
    "Hennersdorf",
    "Hermagor",
    "Hernstein",
    "Herrnbaumgarten",
    "Herzogenburg",
    "Herzogsdorf",
    "Himberg",
    "Himmelreich",
    "Hinterbruehl",
    "Hinterburg",
    "Hinterglemm",
    "Hintersdorf",
    "Hinterstoder",
    "Hinterthiersee",
    "Hintertux",
    "Hinterwaldberg",
    "Hipping",
    "Hirm",
    "Hirschegg",
    "Hirtenberg",
    "Hochburg",
    "Hochgurgl",
    "Hochleithen",
    "Hochneukirchen",
    "Hochsoelden",
    "Hochst",
    "Hoehe",
    "Hof am Leithaberge",
    "Hof bei Salzburg",
    "Hofen",
    "Hofkirchen im Traunkreis",
    "Hoflein",
    "Hofstatten an der Raab",
    "Hofstetten",
    "Hohenau",
    "Hohenberg",
    "Hohenburg",
    "Hoheneich",
    "Hohenems",
    "Hohentauern",
    "Hohenwarth",
    "Hohenzell",
    "Hohnhart",
    "Hollabrunn",
    "Hollenthon",
    "Hollersbach im Pinzgau",
    "Holzhausen",
    "Hopfgarten im Brixental",
    "Horbranz",
    "Horersdorf",
    "Horn",
    "Hornstein",
    "Horsching",
    "Huetten",
    "Huttschlag",
    "Igls",
    "Im Brand",
    "Imst",
    "Innerkrems",
    "Innermanzing",
    "Innsbruck",
    "Inzersdorf im Kremstal",
    "Inzing",
    "Ischgl",
    "Isper",
    "Jagenbach",
    "Jagerberg",
    "Japons",
    "Jeging",
    "Jenbach",
    "Jennersdorf",
    "Jerzens",
    "Jochberg",
    "Jois",
    "Judenau",
    "Judenburg",
    "Judendorf",
    "Jungholz",
    "Kainach bei Voitsberg",
    "Kaindorf",
    "Kalsdorf bei Graz",
    "Kaltenbrunn",
    "Kaltenleutgeben",
    "Kanzelhoehe",
    "Kapelln",
    "Kapfenberg",
    "Kapfing",
    "Kappern",
    "Kappl",
    "Kaprun",
    "Karl",
    "Karlstetten",
    "Karteis",
    "Katsdorf",
    "Katzelsdorf",
    "Kaumberg",
    "Kefermarkt",
    "Kematen in Tirol",
    "Kennelbach",
    "Keutschach am See",
    "Kienberg",
    "Kierling",
    "Kilb",
    "Kindberg",
    "Kirchbach in Steiermark",
    "Kirchberg am Wagram",
    "Kirchberg in Tirol",
    "Kirchbichl",
    "Kirchdorf an der Krems",
    "Kirchdorf in Tirol",
    "Kirchham",
    "Kirchschlag",
    "Kirchschlag bei Linz",
    "Kittsee",
    "Klagenfurt",
    "Klam",
    "Klaus",
    "Klein-Harras",
    "Kleinbergl",
    "Kleinkirchheim",
    "Kleinstubing",
    "Klingfurth",
    "Klosterle",
    "Klostermarienberg",
    "Klosterneuburg",
    "Knappenberg",
    "Knittelfeld",
    "Kobenz",
    "Kobersdorf",
    "Koblach",
    "Koestenberg",
    "Koetschach",
    "Koflach",
    "Kollmitzberg",
    "Konigstetten",
    "Konigswiesen",
    "Kopfing im Innkreis",
    "Koppl",
    "Korneuburg",
    "Kossen",
    "Kottingbrunn",
    "Kottmannsdorf",
    "Kraig",
    "Kramsach",
    "Krems",
    "Kremsbruecke",
    "Kremsdorf",
    "Kremsmunster",
    "Krenglbach",
    "Kreuz",
    "Krieglach",
    "Krispl",
    "Kritzendorf",
    "Kroatisch Minihof",
    "Krottendorf bei Ligist",
    "Krumbach",
    "Krumbach Markt",
    "Krumegg",
    "Krumpendorf",
    "Kuchl",
    "Kuehnsdorf",
    "Kuehtai",
    "Kufstein",
    "Kumberg",
    "Kundl",
    "Laa an der Thaya",
    "Laab im Walde",
    "Laaben",
    "Laakirchen",
    "Labach",
    "Lambrechten",
    "Lamprechtshausen",
    "Landeck",
    "Landegg",
    "Landskron",
    "Lanersbach",
    "Langeck im Burgenland",
    "Langenlois",
    "Langenrohr",
    "Langenstein",
    "Langenzersdorf",
    "Lannach",
    "Lanzenkirchen",
    "Lassee",
    "Lassnitzhohe",
    "Latschach",
    "Launsdorf",
    "Lauterach",
    "Lavamund",
    "Lavant",
    "Laxenburg",
    "Lebring",
    "Lech",
    "Lechaschau",
    "Leibnitz, Styria",
    "Leisach",
    "Leiten",
    "Leitring",
    "Lembach im Muhlkreis",
    "Lend",
    "Lendorf",
    "Lenzing",
    "Leoben",
    "Leobendorf",
    "Leobersdorf",
    "Leogang",
    "Leonding",
    "Leonfelden",
    "Leopoldsdorf",
    "Lermoos",
    "Leutasch",
    "Leutschach",
    "Lichtenau",
    "Lichtenberg",
    "Lichtenegg",
    "Lichtenworth",
    "Liebenfels",
    "Lieboch",
    "Lienz",
    "Liesfeld",
    "Liezen",
    "Ligist",
    "Lilienfeld",
    "Lindenberg",
    "Linz",
    "Litschau",
    "Lobenstein",
    "Lochau",
    "Lochen",
    "Lofer",
    "Lohnsburg",
    "Loimersdorf",
    "Loipersbach",
    "Loosdorf",
    "Loretto",
    "Ludesch",
    "Luftenberg an der Donau",
    "Lungotz",
    "Lustenau",
    "Lutzmannsburg",
    "Mader",
    "Madseit",
    "Maglern",
    "Maiersdorf",
    "Maildorf",
    "Mairhof",
    "Maissau",
    "Mallnitz",
    "Mandling",
    "Mank",
    "Mannersdorf am Leithagebirge",
    "Mannersdorf an der Rabnitz",
    "Mannsworth",
    "Marbach",
    "Marchegg",
    "Marchtrenk",
    "Margarethen am Moos",
    "Maria Alm am Steinernen Meer",
    "Maria Buch",
    "Maria Elend",
    "Maria Ellend",
    "Maria Enzersdorf",
    "Maria Lankowitz",
    "Maria Lanzendorf",
    "Maria Saal",
    "Maria Schmolln",
    "Maria Taferl",
    "Maria Worth",
    "Maria-Anzbach",
    "Mariazell",
    "Markgrafneusiedl",
    "Markt Allhau",
    "Markt Neuhodis",
    "Markt Piesting",
    "Marktl",
    "Marz",
    "Mathon",
    "Matrei am Brenner",
    "Matrei in Osttirol",
    "Mattersburg",
    "Mattsee",
    "Mauerbach",
    "Mauerkirchen",
    "Maurach",
    "Mauterndorf",
    "Mauthausen",
    "Mayrhofen",
    "Meggenhofen",
    "Mehrnbach",
    "Meiningen",
    "Meisten",
    "Melk",
    "Mellach",
    "Mettmach",
    "Michelbach Markt",
    "Micheldorf in Oberoesterreich",
    "Mieming",
    "Miesenbach",
    "Miesenbach",
    "Millstatt",
    "Mistelbach",
    "Mittelberg",
    "Mitterdorf im Muerztal",
    "Mitterkirchen im Machland",
    "Mitterndorf an der Fischa",
    "Mittersill",
    "Moellbruecke",
    "Mollersdorf",
    "Molln",
    "Mollram",
    "Monchhof",
    "Mondsee",
    "Moos",
    "Moosburg",
    "Moosdorf",
    "Mooskirchen",
    "Mosern",
    "Motz",
    "Muckendorf an der Donau",
    "Muerzhofen",
    "Muerzsteg",
    "Muerzzuschlag",
    "Muhlbach am Manhartsberg",
    "Munchendorf",
    "Muntlix",
    "Munzbach",
    "Munzkirchen",
    "Murau",
    "Murfeld",
    "Mutters",
    "Naarn im Machlande",
    "Nassereith",
    "Natternbach",
    "Nauders",
    "Neckenmarkt",
    "Neidling",
    "Nenzing",
    "Nesselwangle",
    "Nestelbach bei Graz",
    "Neudau",
    "Neudorf bei Landsee",
    "Neudorf bei Staatz",
    "Neudorfl",
    "Neufeld an der Leitha",
    "Neuhofen",
    "Neuhofen an der Krems",
    "Neuhofen an der Ybbs",
    "Neukirchen",
    "Neukirchen am Walde",
    "Neukirchen an der Enknach",
    "Neukirchen an der Vockla",
    "Neulengbach",
    "Neumarkt am Wallersee",
    "Neumarkt an der Ybbs",
    "Neumarkt im Hausruckkreis",
    "Neumarkt im Muhlkreis",
    "Neumarkt in Steiermark",
    "Neunkirchen",
    "Neusiedl am See",
    "Neusiedl bei Guessing",
    "Neustift",
    "Neutal",
    "Neuzeug",
    "Nickelsdorf",
    "Niederachen",
    "Niederalm",
    "Niederdorf",
    "Niederkreuzstetten",
    "Niederland",
    "Niederleis",
    "Niederndorf",
    "Niederneukirchen",
    "Niederwaldkirchen",
    "Niederwolz",
    "Nochling",
    "Nussdorf",
    "Nussdorf am Haunsberg",
    "Nuziders",
    "Obdach",
    "Ober-Grafendorf",
    "Oberaich",
    "Oberaichwald",
    "Oberalm",
    "Oberau",
    "Obergruenburg",
    "Obergurgl",
    "Oberhausen",
    "Oberhofen im Inntal",
    "Oberkappel",
    "Oberkirchbach",
    "Oberkohlstaetten",
    "Obernberg",
    "Obernberg am Brenner",
    "Oberndorf an der Melk",
    "Oberndorf bei Salzburg",
    "Oberneukirchen",
    "Oberort",
    "Oberperfuss",
    "Oberpullendorf",
    "Oberrohrbach",
    "Oberschutzen",
    "Obersdorf",
    "Obersiebenbrunn",
    "Obertauern",
    "Obertrum am See",
    "Obervellach",
    "Oberwaltersdorf",
    "Oberwart",
    "Oberweis",
    "Oberwolbling",
    "Obritzberg",
    "Obsteig",
    "Oed",
    "Oehling",
    "Oepping",
    "Oetz",
    "OEtztal-Bahnhof",
    "Offenhausen",
    "Oftering",
    "Oggau",
    "Ohlsdorf",
    "Ollern",
    "Opponitz",
    "Ort im Innkreis",
    "Orth an der Donau",
    "Oslip",
    "Ossiach",
    "Ostermiething",
    "Ottendorf bei Gleisdorf",
    "Ottenheim",
    "Ottensheim",
    "Pabneukirchen",
    "Pachfurth",
    "Paldau",
    "Panzendorf",
    "Parndorf",
    "Parschlug",
    "Pasching",
    "Passail",
    "Passthurn",
    "Patsch",
    "Pattergassen",
    "Payerbach",
    "Peggau",
    "Perchtoldsdorf",
    "Perg",
    "Pernegg an der Mur",
    "Pernitz",
    "Pertisau",
    "Perwang am Grabensee",
    "Petersdorf",
    "Petronell-Carnuntum",
    "Pettenbach",
    "Pettnau",
    "Pettneu",
    "Petzenkirchen",
    "Peuerbach",
    "Pfaffstatten",
    "Pfons",
    "Pfunds",
    "Piberbach",
    "Pichl",
    "Pichl bei Wels",
    "Pichling bei Stainz",
    "Piesendorf",
    "Pillberg",
    "Pillichsdorf",
    "Pinggau",
    "Pinkafeld",
    "Pinsdorf",
    "Piringsdorf",
    "Pirka",
    "Pischeldorf",
    "Pischelsdorf am Engelbach",
    "Pischelsdorf in Steiermark",
    "Pitten",
    "Plangeross",
    "Plankenau",
    "Plescherken",
    "Pochlarn",
    "Poelten",
    "Poertschach am Woerthersee",
    "Poetting",
    "Poggstall",
    "Polfing",
    "Pottelsdorf",
    "Pottenbrunn",
    "Pottendorf",
    "Pottenstein",
    "Pottsching",
    "Potzneusiedl",
    "Poysbrunn",
    "Poysdorf",
    "Prabach",
    "Pram",
    "Preding",
    "Pregarten",
    "Pressbaum",
    "Prinzersdorf",
    "Puch",
    "Puch bei Hallein",
    "Puchberg am Schneeberg",
    "Puchenau",
    "Pucking",
    "Purbach",
    "Purbach am Neusiedlersee",
    "Purgg",
    "Purgstall",
    "Purgstall",
    "Purkersdorf",
    "Pyhra",
    "Raab",
    "Raaba",
    "Raabs an der Thaya",
    "Radfeld",
    "Radstadt",
    "Ramsau im Zillertal",
    "Randegg",
    "Rangersdorf",
    "Rankweil",
    "Rannersdorf",
    "Rappoltenkirchen",
    "Rauchenwarth",
    "Rauris",
    "Redlham",
    "Regau",
    "Regelsbrunn",
    "Reichenau an der Rax",
    "Reichenau im Muhlkreis",
    "Reichendorf",
    "Reichraming",
    "Reifnitz",
    "Reisenberg",
    "Reitdorf",
    "Reith",
    "Reith bei Seefeld",
    "Reith im Alpbachtal",
    "Rekawinkel",
    "Reutte",
    "Ried im Innkreis",
    "Ried im Traunkreis",
    "Ried im Zillertal",
    "Ried in der Riedmark",
    "Riedenthal",
    "Rieding",
    "Riedlingsdorf",
    "Riefensberg",
    "Riegersburg",
    "Riezlern",
    "Ringelsdorf",
    "Rinn",
    "Rohrau",
    "Rohrbach am Kulm",
    "Rohrbach am Steinfelde",
    "Rohrbach in Oberosterreich",
    "Rohrmoos",
    "Roppen",
    "Rosegg",
    "Rosenau am Hengstpass",
    "Rosenbach",
    "Rosental",
    "Rosental",
    "Rotenbach",
    "Rothis",
    "Rotholz",
    "Rottenbach",
    "Rottenmann",
    "Rubring",
    "Ruden",
    "Rudersdorf",
    "Rum",
    "Rutzenmoos",
    "Saalbach",
    "Saalfelden am Steinernen Meer",
    "Sachendorf",
    "Sachsenburg",
    "Saint Anton",
    "Salzburg",
    "Sankt Agatha",
    "Sankt Andra am Zicksee",
    "Sankt Andrae",
    "Sankt Florian",
    "Sankt Gallenkirch",
    "Sankt Georgen am Ybbsfelde",
    "Sankt Georgen im Attergau",
    "Sankt Johann im Pongau",
    "Sankt Kanzian",
    "Sankt Kathrein am Hauenstein",
    "Sankt Lorenzen",
    "Sankt Lorenzen im Muerztal",
    "Sankt Margarethen im Burgenland",
    "Sankt Marienkirchen am Hausruck",
    "Sankt Martin am Techelsberg",
    "Sankt Martin am Ybbsfelde",
    "Sankt Michael im Burgenland",
    "Sankt Michael in Obersteiermark",
    "Sankt Oswald",
    "Sankt Pankraz",
    "Sankt Peter",
    "Sankt Polten",
    "Sankt Ruprecht an der Raab",
    "Sankt Stefan im Rosental",
    "Sankt Ulrich bei Steyr",
    "Sankt Valentin",
    "Sankt Veit an der Glan",
    "Sankt Veit im Pongau",
    "Sankt Wolfgang",
    "Sankt Wolfgang",
    "Sarleinsbach",
    "Satteins",
    "Sauerbrunn",
    "Sausenstein",
    "Schachendorf",
    "Schalchen",
    "Schardenberg",
    "Scharding",
    "Scharnstein",
    "Scharten",
    "Schattendorf",
    "Scheffau am Wilden Kaiser",
    "Scheifling",
    "Schiefling am See",
    "Schladming",
    "Schleinbach",
    "Schlierbach",
    "Schlins",
    "Schlitters",
    "Schmirn",
    "Schneeberg",
    "Schoenau",
    "Schoenberg im Stubaital",
    "Schoerfling",
    "Schonbuhel an der Donau",
    "Schongrabern",
    "Schonkirchen",
    "Schoppernau",
    "Schrems",
    "Schruns",
    "Schutzen am Gebirge",
    "Schwadorf",
    "Schwaigs",
    "Schwanberg",
    "Schwanenstadt",
    "Schwarzach",
    "Schwarzach im Pongau",
    "Schwarzau am Steinfelde",
    "Schwarzau im Gebirge",
    "Schwarzenau",
    "Schwarzenberg am Boehmerwald",
    "Schwaz",
    "Schwechat",
    "Schweiggers",
    "Schwendau",
    "Schwertberg",
    "Schwoich",
    "Sebersdorf",
    "Seckau",
    "Seeboden",
    "Seefeld in Tirol",
    "Seeham",
    "Seekirchen am Wallersee",
    "Seewalchen",
    "Seiersberg",
    "Seitenstetten Markt",
    "Semmering",
    "Semriach",
    "Serfaus",
    "Sernau",
    "Sibratsgfall",
    "Siebenhirten",
    "Siebenhirten",
    "Siegendorf im Burgenland",
    "Sieghartskirchen",
    "Sierndorf",
    "Sierning",
    "Siezenheim",
    "Sillian",
    "Silz",
    "Sinabelkirchen",
    "Sinnersdorf",
    "Sipbachzell",
    "Sirnitz",
    "Sistrans",
    "Sitzenberg",
    "Solden",
    "Soll",
    "Sollenau",
    "Sommerein",
    "Sooss",
    "Spielberg bei Knittelfeld",
    "Spillern",
    "Spital am Pyhrn",
    "Spittal an der Drau",
    "Spitz",
    "Spratzern",
    "Staatz",
    "Stadelbach",
    "Stadl-Paura",
    "Stadtschlaining",
    "Stainz",
    "Stainz bei Straden",
    "Stams",
    "Stans",
    "Stattegg",
    "Statzendorf",
    "Steg",
    "Stegersbach",
    "Stein an der Donau",
    "Stein an der Enns",
    "Stein im Jauntal",
    "Steinabruckl",
    "Steinach am Brenner",
    "Steinakirchen am Forst",
    "Steinberg bei Ligist",
    "Steindorf am Ossiacher See",
    "Steinerberg",
    "Steinerkirchen an der Traun",
    "Steinfeld",
    "Steinhaus",
    "Steinhaus am Semmering",
    "Stettenhof",
    "Steyr",
    "Steyregg",
    "Stiegl",
    "Stockerau",
    "Stoob",
    "Straden",
    "Strass",
    "Strassen",
    "Strassengel",
    "Strasshof an der Nordbahn",
    "Strasswalchen",
    "Strau",
    "Strobl",
    "Stubach",
    "Stubenberg",
    "Studenzen",
    "Stuhlfelden",
    "Stuhlsdorf",
    "Stumm",
    "Stummerberg",
    "Sulz",
    "Sulz im Wienerwald",
    "Sulzau",
    "Sulzberg",
    "Tadten",
    "Tal",
    "Tamsweg",
    "Tannheim",
    "Tarrenz",
    "Tattendorf",
    "Taufkirchen an der Pram",
    "Taufkirchen an der Trattnach",
    "Tauplitz",
    "Taxenbach",
    "Telfes im Stubai",
    "Telfs",
    "Ternberg",
    "Ternitz",
    "Teufenbach",
    "Thal",
    "Thalgau",
    "Thalheim bei Wels",
    "Thalling",
    "Thaur",
    "Thaya",
    "Theresienfeld",
    "Thoerl",
    "Thuringen",
    "Tiefenbach",
    "Tiefgraben",
    "Tieschen",
    "Tirol",
    "Tobaj",
    "Toeschling",
    "Toesenssteinach",
    "Traboch",
    "Traisen",
    "Traiskirchen",
    "Traismauer",
    "Trasdorf",
    "Traun",
    "Traunkirchen",
    "Traunstein",
    "Trausdorf an der Wulka",
    "Trautmannsdorf an der Leitha",
    "Tribuswinkel",
    "Trieben",
    "Tristach",
    "Troepolach",
    "Trofaiach",
    "Trumau",
    "Tschagguns",
    "Tschoeran",
    "Tulln",
    "Tullnerbach-Lawies",
    "Tumeltsham",
    "Turnitz",
    "Turrach",
    "Tweng",
    "Uderns",
    "Ulmerfeld",
    "Ulrichsberg",
    "Ulrichskirchen",
    "Ungenach",
    "Unterberg",
    "Untergrub",
    "Unterjoch",
    "Unterlamm",
    "Unterparschenbrunn",
    "Unterpremstatten",
    "Unterpullendorf",
    "Unterpurkla",
    "Unterradlberg",
    "Unterrohr",
    "Unterrohr",
    "Untersiebenbrunn",
    "Unterwaltersdorf",
    "Unterweitersdorf",
    "Unzmarkt",
    "Uttendorf",
    "Utzenaich",
    "Veitsch",
    "Velden am Woerthersee",
    "Vent",
    "Vienna",
    "Vigaun",
    "Viktorsberg",
    "Viktring",
    "Villach",
    "Virgen",
    "Vitis",
    "Vocklabruck",
    "Vocklamarkt",
    "Voelkermarkt",
    "Voitsberg",
    "Volders",
    "Vols",
    "Vorau",
    "Vorchdorf",
    "Vorderlanersbach",
    "Vordernberg",
    "Vosendorf",
    "Wagna",
    "Wagrain",
    "Waidhofen an der Thaya",
    "Waidhofen an der Ybbs",
    "Waidmannsfeld",
    "Waidring",
    "Waizenkirchen",
    "Walbersdorf",
    "Walchsee",
    "Wald am Arlberg",
    "Waldenstein",
    "Walding",
    "Waldkirchen am Wesen",
    "Waldzell",
    "Wallern an der Trattnach",
    "Wallern im Burgenland",
    "Wallsee",
    "Wals",
    "Waltersdorf an der March",
    "Waltersdorf in Oststeiermark",
    "Wampersdorf",
    "Wang",
    "Wangle",
    "Wartberg",
    "Wartberg an der Krems",
    "Warth",
    "Warth",
    "Wattens",
    "Watzelsdorf",
    "Watzendorf",
    "Waxenberg",
    "Weibern",
    "Weiden am See",
    "Weigelsdorf",
    "Weikendorf",
    "Weikersdorf am Steinfelde",
    "Weilbach",
    "Weiler",
    "Weinburg am Sassbach",
    "Weissbriach",
    "Weissenbach am Lech",
    "Weissenkirchen in der Wachau",
    "Weisskirchen an der Traun",
    "Weisskirchen in Steiermark",
    "Weiten",
    "Weitersfeld",
    "Weitra",
    "Weiz",
    "Wels",
    "Weng bei Admont",
    "Weng im Innkreis",
    "Wenns",
    "Weppersdorf",
    "Werfen",
    "Werfenweng",
    "Werndorf",
    "Wernstein am Inn",
    "Westendorf",
    "Wettmannstatten",
    "Wiener Neudorf",
    "Wiener Neustadt",
    "Wienerherberg",
    "Wies",
    "Wieselburg",
    "Wiesing",
    "Wiesmath",
    "Wieting",
    "Wildon",
    "Wilfleinsdorf",
    "Wilhelmsburg",
    "Wilhering",
    "Wimpassing an der Leitha",
    "Wimpassing im Schwarzatale",
    "Winden am See",
    "Windischgarsten",
    "Winkl",
    "Winzendorf",
    "Woelfnitz",
    "Wolfau",
    "Wolfpassing",
    "Wolfsberg",
    "Wolfsgraben",
    "Wolfurt",
    "Wolkersdorf im Weinviertel",
    "Wollersdorf",
    "Wordern",
    "Worgl",
    "Wulkaprodersdorf",
    "Wundschuh",
    "Wurflach",
    "Wurmbrand",
    "Ybbs an der Donau",
    "Ybbsitz",
    "Zams",
    "Zeillern",
    "Zeiselmauer",
    "Zell am Moos",
    "Zell am See",
    "Zell am Ziller",
    "Zell an der Ybbs",
    "Zellerndorf",
    "Zeltweg",
    "Zemendorf",
    "Zettling",
    "Ziersdorf",
    "Zillingdorf",
    "Zillingtal",
    "Zipf",
    "Zirl",
    "Zistersdorf",
    "Zobing",
    "Zuers",
    "Zurndorf",
    "Zwentendorf",
    "Zwettl Stadt",
    "Zwolfaxing"
  ];
  }
}
